services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca-jogos-api
    image: biblioteca-jogos-api
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html:cached
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public